{% set name = "datatables" %}
{% set version = "1.10.19" %}
{% set sha256 = "46b2ed352cc119e0bb0442ea153db3ce2252e5a34fe20e5211a0de909ce7558e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DataTables/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g datatables
  requires:
    - nodejs
   

about:
  home: https://github.com/DataTables/DataTables
  license: MIT
  license_family: MIT
  license_file: license.txt
  summary: 'Tables plug-in for jQuery'
  description: |
    DataTables is a table enhancing plug-in for the jQuery Javascript library, 
    adding sorting, paging and filtering abilities to plain HTML tables with minimal effort.  
  doc_url: https://datatables.net/
  dev_url: https://github.com/DataTables/DataTables

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
