travis:
  secure:
    BINSTAR_TOKEN: I8bhICGDa37Erc7pNbX/RZSy6DOEg9fFy3mV5rTh7DkOBOMhE8endwGYReX2DS27qg9CGRicGLjY0GW6M4A4P8zGXEjOXzbJe5tbeLW28h0R7+9/Mzv/m+QJw1CX5utbGwgMKQOw+FK0DdeNwwtmx3UFsbc36i7nldYIjrcc/aGcG0gbAVoxwWKjcpObu93naNSAvffkssX6r+vsQl3IqzS/l6o9jCf8i1D9pb8TTGo30X1SpoE6BsviH91edlomjQxEnrjOUgqqm4V+LxpRimMiSzMe6tC3maD4mv6mi+GNgkheLo7V4R4hPpNGfewHOyaHnn/Hs294VgYg6hK5sEllJFFv1rRCo+2UlgRz7HFYJL7J4s4HkqnNzJSGTnDIG2oobddzKmgNuwEtEyTGNsOlnyEixNzxWPKyH1mU4Hk0kC1KupT+rbw7hSqP8tMFTp5/2PeaidHwi4+2q/AAh44sNr3UZWprv3GGc9pnyu1vqsHyKiEKFsO6HR8huO4fXvC++Lpz00lrxdh3xnixgH0IVHY4qtZ1V6gDg0qu+DdIQLfpkOjKcKqFPK3pL7D0NJH+UneN5uxbRpIo3KN/fs9w8B+9zCbjX+Jg6MFvNuYFODekAHu51rnpuf2ruqPQi0zNrq3EcRT5BwknfOWAhpcqRMrwJ/WFhokLEKyJJbs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
