travis:
  secure:
    BINSTAR_TOKEN: LaUshEGecWbbz/Yv+zbs6SiE0Ho8m0gkp5NIyveKAj71+mYyGIT5XK1ikYRfCZ1jT/O/DUwDVBDSRbN1XFxr1BkfBXeMS3k6XahyFavpFzFHbU1RAy2Aaf8FbiT/JJEB0RCJ+YEIVB2MNdejudID7YjR53Ji38Y1arhnGnRYMokGtZHyHFZVrokuqSrjl6cthPAux99STlMv4bm766g08MFd1z5+cbtUSV5A+AR/7IeXPpXYxANfV0f+XpyJs47fBJZQ4zQbiTwgDpOd/AqyP+pAHnuBt8O3QzcgtzuluiMjwhWzHTIfCRpZu4RUGPofBwHCn9EzaODubvnHj0gP9UlKQKGhGxRpdbkSZTsXbY3xn23U1VOECMZ+njiEVi5c6Muux8kU6udxQ3brpo8+oh5RLTNYC/zOdwIMiAcdPymFMvhsd91KceiQB6RnQEVz+IMGyDbTSUxNoV1TMtmExzqB8zV/h4Gtm1ze46ufj1cVI1tiNbc8Mu2o6BjpjacrV7opX1hbddQvu6O8yqws8mE90njWNUvbO8gXUsICcNvm9sWhoagGEzjiM3KS67sNs2uOMwLvOEb7Ofrs01VhD9GRMu105h4L5iqywbTCHjBk/FlAs8DbeTeFPe+HrcoBEUZr8zJEy6I7KFPBSbHzQJx0auwuw7tBkiR0B6mltxQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
